#========================server配置====================================================================================#
server:
  port: 8090
app:
  id: shimaoiot
apollo:
  meta: http://172.19.59.48:9100
  bootstrap:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka} #http://i6u05EJR:i6u05EJR@172.19.61.38:8761/eureka,http://i6u05EJR:i6u05EJR@172.19.61.39:8761/eureka,http://i6u05EJR:i6u05EJR@172.19.61.40:8761/eureka
    registerWithEureka: true
    fetchRegistry: true
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
#========================mysql数据库配置===============================================================================#
spring:
  application:
    name: user-server
  datasource:
    #url: jdbc:mysql://172.19.61.40:3306/shimao-iot?characterEncoding=utf8&useSSL=false
    url: ${mysql.shimao-iot-user}
    username: ${mysql.username}
    password: ${mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: ${kafka}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: shimao-device-server
      enable-auto-commit: true
      auto-commit-interval: 1000s
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  elasticsearch:
    jest:
      uris:
        - ${elk}
    read-timeout: 5000

#========================mybatis映射配置===============================================================================#
mybatis:
  typeAliasesPackage: com.shimao.iot.userserver
  mapperLocations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true

logging:
   config: classpath:logback-spring.xml
path:
    log: /opt