#========================server配置====================================================================================#
server:
  port: 8090
#========================mysql数据库配置===============================================================================#
spring:

  #============================应用配置===========================================================================#
  application:
    name: office-user

  datasource:
    #   本地数据库
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&autoReconnect=true
    username: root
    password: 123456
    #   远程数据库
    #    url: jdbc:mysql://120.79.250.62:9936/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&autoReconnect=true
    #    username: shareaio
    #    password: zhly@2015
    driver-class-name: com.mysql.cj.jdbc.Driver

#========================mybatis映射配置===============================================================================#
mybatis:
  typeAliasesPackage: com.office.user
  mapperLocations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
  #=========================邮箱配置（我这里使用163）==============================================================================#

#  mail:
#  host: smtp.163.cn
#  username: li_chao_cheng@163.com
#  password: Cc360428
#  port: 25
#  default-encoding: UTF-8
#  protool: stmp
#  properties:
#    mail:
#      smth:
#        auth: true
#        strttls:
#          enable: true
#          required: true
  mail:
    host: smtp.163.com                 #邮箱服务器地址
    username: li_chao_cheng@163.com  #邮箱账号
    password: Cc360428            #邮箱密码
    default-encoding: utf-8          #默认编码
    #    properties:
    #      smtp:
    #        auth:true
    #        timeout:25000
    #邮件发件人
    fromMail:
      addr: li_chao_cheng@163.com
