#========================server配置====================================================================================#
server:
  port: 8090
spring:
  application:
    #============================应用配置===========================================================================#
    name: office-user
  datasource:
    #   本地数据库
    url: jdbc:mysql://47.244.225.92:9936/practice?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&autoReconnect=true
    username: practice
    password: lichaocheng
    driver-class-name: com.mysql.cj.jdbc.Driver

#========================mybatis映射配置===============================================================================#
mybatis:
  typeAliasesPackage: com.office.user
  mapperLocations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
    #=========================邮箱配置（我这里使用163）==============================================================================#
  mail:
    host: smtp.163.cn
    port: 25
    username: li_chao_cheng@163.com # 这里填写个人的qq邮箱
    password: Cc360428 # 注：这里不是qq邮箱的密码，而是授权码
    properties:
      mail:
        smtp:
        auth: true
        enable: true
        required: true
#=========================redis==============================================================================#
###Redis配置
  redis:
    ###Redis数据库索引（默认为0）
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        ###连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        ###连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        ###连接池中的最大空闲连接
        max-idle: 5
        ###连接池中的最小空闲连接
        min-idle: 0
    ###连接超时时间（毫秒）
    timeout: 0
