#========================server配置====================================================================================#
server:
  port: 8090
spring:
  application:
    #============================应用配置===========================================================================#
    name: office-user
  datasource:
    #   本地数据库
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&autoReconnect=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

#========================mybatis映射配置===============================================================================#
mybatis:
  typeAliasesPackage: com.office.user
  mapperLocations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
    #=========================邮箱配置（我这里使用163）==============================================================================#
  mail:
    host: smtp.163.cn
    port: 25
    username: li_chao_cheng@163.com # 这里填写个人的qq邮箱
    password: Cc360428 # 注：这里不是qq邮箱的密码，而是授权码
    properties:
      mail:
        smtp:
        auth: true
        enable: true
        required: true